metaDataFormat: yaml
disableHugoGeneratorInject: true
hasCJKLanguage: true
title: WebDINO Japan
copyright: WebDINO Japan
baseURL: 'https://www.webdino.org/'
languageCode: ja
assetDir: static
permalinks:
  authors: /updates/author/:slug/
  tags: /updates/tag/:slug/
taxonomies:
  author: authors
  tag: tags
disableKinds:
  - taxonomyTerm
outputs:
  home:
    - HTML
    - RSS
  section:
    - HTML
  term:
    - HTML
rssLimit: 50
markup:
  goldmark:
    extensions:
      typographer: true
    renderer:
      unsafe: true
