metaDataFormat: yaml
disableHugoGeneratorInject: true
hasCJKLanguage: true
title: WebDINO Japan
copyright: WebDINO Japan
baseURL: 'https://www.webdino.org/'
languageCode: ja
assetDir: static
timeout: 500000
permalinks:
  authors: /updates/author/:slug/
  tags: /updates/tag/:slug/
taxonomies:
  author: authors
  tag: tags
outputs:
  home:
    - HTML
    - RSS
  section:
    - HTML
  term:
    - HTML
rssLimit: 50
markup:
  goldmark:
    extensions:
      typographer: true
    renderer:
      unsafe: true
server:
  headers:
    - for: /**
      values:
        Cache-Control: max-age=0, must-revalidate, public
        Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline' 'self' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com/; img-src 'self' https://*.cloudfront.net/ https://*.googletagmanager.com https://*.google-analytics.com https://*.analytics.google.com; script-src 'unsafe-inline' 'self' https://*.googletagmanager.com https://*.google-analytics.com https://*.analytics.google.com; connect-src 'self' https://*.googletagmanager.com https://*.google-analytics.com https://*.analytics.google.com; form-action 'self'; frame-src https://www.google.com https://www.slideshare.net https://www.youtube-nocookie.com; frame-ancestors 'none'; base-uri 'none';
        Strict-Transport-Security: max-age=63072000
        Referrer-Policy: same-origin
        X-Content-Type-Options: nosniff
        X-Frame-Options: DENY
        X-XSS-Protection: 1; mode=block
