[build]
publish = "public"
command = "hugo"

[context.production]

[context.production.environment]
HUGO_VERSION = "0.40.3"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --buildFuture"

[context.deploy-preview.environment]
HUGO_VERSION = "0.40.3"
HUGO_ENV = "production"
# include additional static files for preview site
HUGO_STATICDIR0 = "static-preview"

[context.branch-deploy]
command = "hugo --buildFuture"

[context.branch-deploy.environment]
HUGO_VERSION = "0.40.3"
HUGO_ENV = "production"
# include additional static files for preview site
HUGO_STATICDIR0 = "static-preview"

# references:
# Hugo - command: https://gohugo.io/commands/hugo/
# Hugo - config: https://gohugo.io/getting-started/configuration/
# Hugo - static files: https://gohugo.io/content-management/static-files/

[[redirects]]
  from = "/*"
  to = "/error/"
  status = 404
